const intformat = require('biguint-format');
const FlakeId = require('flake-idgen');

/**
 * Get a unique value generated by flake-idgen
 * @returns {number} Some huge unique number
 */
function getFlakeId() {
  const flakeIdGen1 = new FlakeId();
  return intformat(flakeIdGen1.next(), 'dec');
}

module.exports = getFlakeId;
